server:
  port: 8009
  servlet:
    context-path: /

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/phoneinfo?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: root
    url: jdbc:mysql://127.0.0.1:3306/phoneinfo?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root


mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  type-aliases-package: com.entity

#logging.level.org.springframework.boot.autoconfigure: error
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: error

